setwd("directional address")
source("scoreBoard_strategy.R", local=FALSE)
source("round_180507.R", local=FALSE)
source("evolution_180508.R", local=FALSE)
source("transition_matrix_180509.R", local=FALSE)
source("monte_carlo_simulation_180529.R", local=FALSE)
